services:
  postgres:
    container_name: fuel-management-postgres
    image: postgres:16-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Bangkok
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - fuel-management-postgres-data:/var/lib/postgresql/data
    networks:
      - fuel-management
