database:
  use: "postgres"
  postgres:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "postgres"
    dbname: "fuel"
    sslmode: "disable"
  sqlite:
    filePath: "../fuel-management-backend/test.db"
